spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql:///sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    path: /sell