spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql:///sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    format-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    path: /sell